class PagesController < ApplicationController
  def home
    @reviews = [
      { author: 'Jul', rating: 5, text: "Baptiste n'est pas un ancien danseur professionnel pour rien, son massage est une douce et attentive chorégraphie qui vous fera voyager loin, dans un lieu rare et précieux, au pays de la Détente Totale. Vous en ressortirez complètement relaxé et shooté aux endorphines jusqu'aux yeux. Rassurez-vous, c'est parfaitement légal et normal après un aussi merveilleux moment hors du temps ! Un magnifique cadeau à savourer pour soi-même ou à offrir. Je reviendrai dès que possible !" },
      { author: 'JE R', rating: 5, text: "Un excellent moment. Baptiste a une maîtrise et une technique de massage super agréable et efficace. Se détendre, oublier son corps se laisser aller au rythme des mouvements…  24h après j en ai encore des bénéfices. Merci à Baptiste pour son professionnalisme son accueil et son écoute. Je conseille a tout le monde une heure de massage si vous êtes dans le coin." },
      { author: 'Jean-Philippe', rating: 5, text: "Excellente expérience avec Baptiste ! Le massage est de grande qualité. Beaucoup de confort et de délicatesse dans les mouvements. Je ressens les effets des jours après, notamment sur des douleurs que je ressentais depuis longtemps. De plus, Baptiste est très accueillant, à l'écoute et extrêmement sympathique. La prise de rendez-vous est facile, tout comme de nombreuses places de stationnement sont accessibles juste en bas de l'immeuble. Je recommande très vivement pour un moment de détente et de relaxation à part entière ! Je ne manquerai personnellement pas de revenir lorsque je serai à nouveau de passage dans le secteur."},
      { author: 'Natacha', rating: 5, text: "Baptiste est un masseur hors pair, d'un grand professionnalisme. Sa maitrise et sa connaissance parfaite du corps, font de ses massages une expérience unique. Je suis arrivée tendue, respirant à peine, le cerveau en ébullition ! Je suis repartie telle une plume  j'ai tout lâché et laissé sur la table de massage. MERCI ❤️" },
      { author: 'Céline', rating: 5, text: "Un mélange de douceur et de relaxation. Baptiste est un excellent masseur, qui prête attention aux détails. Allez-y les yeux fermés..et ce jusqu'à la fin du massage 💫" },
      { author: 'Christine', rating: 5, text: "Premier foot massage avec Baptiste. Agréablement surprise par ce massage complet et profond. Je recommande ce massage pour la qualité de la prestation, des gestes techniques et sûrs. Merci encore pour ce moment de détente après une longue journée de travail." },
      { author: 'Eva', rating: 5, text: "Massage Kobido avec Baptiste incroyable. Une vraie sensation de lifting et un résultat bluffant ! Un touché adapté au client, un pure moment de relaxation et de bien être. Je recommande +++" },
      { author: 'Mathilde', rating: 5, text: "Très belle découverte du massage Kobido, alliant douceur et tonicité. Résultat immédiat, tant au niveau du visage qui retrouve de l’éclat, mais aussi une profonde détente!! Moment très agréable avec Baptiste, merci." },
      { author: 'Jean-Noel', rating: 5, text: "Baptiste est un excellent masseur. Il sait combiner à la fois les techniques douces venues d'Asie et autres, et si besoin il peut également aller sur des massages décontractant plus appuyés pour sportifs. Je le recommande sans hésiter pour tout le monde qui désire avoir un massage de haut niveau." }
    ]
  end
end
